### ISSUE TITLE
Puppet agent stuck on call to docker version

### ISSUE THREAD

**Issue by damonmaria** [puppetlabs/puppetlabs-docker#547]
## Describe the Bug
I have 2 machines that I setup with only `include docker`. They do not have any other docker resources. On both machines the puppet agent service stops calling in and it appears to be stuck calling out to `docker version`. 

```
# systemctl status puppet.service 
* puppet.service - Puppet agent
   Loaded: loaded (/lib/systemd/system/puppet.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-11-03 21:56:16 NZDT; 1 day 20h ago
 Main PID: 10533 (puppet)
    Tasks: 32 (limit: 4915)
   CGroup: /system.slice/puppet.service
           |-  823 puppet agent: applying configuration
           |-  890 sh -c /usr/bin/docker version --format '{{json .}}'
           |-  891 /usr/bin/docker version --format {{json .}}
           `-10533 /opt/puppetlabs/puppet/bin/ruby /opt/puppetlabs/puppet/bin/puppet agent --no-daemonize

Nov 05 16:26:17 proc1 puppet-agent[9491]: Run of Puppet configuration client already in progress; skipping 
Nov 05 16:26:17 proc1 puppet[10533]: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:94:in `for
Nov 05 16:56:17 proc1 puppet-agent[9503]: Run of Puppet configuration client already in progress; skipping 
Nov 05 16:56:17 proc1 puppet[10533]: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:94:in `for
Nov 05 17:26:17 proc1 puppet-agent[9579]: Run of Puppet configuration client already in progress; skipping 
Nov 05 17:26:17 proc1 puppet[10533]: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:94:in `for
Nov 05 17:56:17 proc1 puppet-agent[9597]: Run of Puppet configuration client already in progress; skipping 
Nov 05 17:56:17 proc1 puppet[10533]: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:94:in `for

# ps -ef | grep docker
root       890   823  0 Nov03 ?        00:00:00 sh -c /usr/bin/docker version --format '{{json .}}'
root       891   890  0 Nov03 ?        00:00:27 /usr/bin/docker version --format {{json .}}
root     10089     1  0 18:27 ?        00:00:01 /usr/bin/dockerd -H unix:///var/run/docker.sock --ip-forward=true --iptables=true --ip-masq=true -G docker
root     10284  9561  0 18:33 pts/2    00:00:00 grep --color=auto docker
```

So you can see the call to `docker version` (pids 890/891) has been running for 2 days! 

If I copy the `sh -c /usr/bin/docker version --format '{{json .}}'` command (from the `ps` output) and run i it works. But if I copy the child process of that (pid 891) `/usr/bin/docker version --format {{json .}}` it fails (but exits with an error). This is due to the missing quotes. I'm not sure if this is just formatting issue in the `ps` output. 

So I have no idea how this docker command could hang but also shouldn't there be a timeout limit on this call? Probably every call run by Facter?  

## Expected Behavior
Puppet agent calls in on schedule. 

## Steps to Reproduce
Literally the only mention of docker in my manifest is `include docker`. So I dunno what's special about my setup that causes this. 

## Environment
```
# puppet --version
6.10.1
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
# docker version
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:59:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:58:31 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

From Puppetfile: `mod 'puppetlabs-docker', '3.8.0'`

## Additional Context
My attempt at debugging:
```
# sudo systemctl stop puppet.service 
# puppet agent -t
Notice: Run of Puppet configuration client already in progress; skipping  (/opt/puppetlabs/puppet/cache/state/agent_catalog_run.lock exists)
# systemctl status puppet.service 
* puppet.service - Puppet agent
   Loaded: loaded (/lib/systemd/system/puppet.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2019-11-05 18:40:15 NZDT; 14s ago
  Process: 10533 ExecStart=/opt/puppetlabs/puppet/bin/puppet agent $PUPPET_EXTRA_OPTS --no-daemonize (code=
 Main PID: 10533 (code=exited, status=0/SUCCESS)
    Tasks: 30 (limit: 4915)
   CGroup: /system.slice/puppet.service
           |-823 puppet agent: applying configuration
           |-890 sh -c /usr/bin/docker version --format '{{json .}}'
           `-891 /usr/bin/docker version --format {{json .}}
...
```

The processes weren't stopped by stopping the service. I had to manually kill them. 

```
# puppet agent -t
Info: Using configured environment 'tannery_production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for proc1.XXX
Info: Applying configuration version 'ea1ea2bc8c1daafc1244b71f93cf73fd110cdce5'
Notice: Applied catalog in 1.24 seconds
```

So agent can run OK. 

```
# systemctl start puppet.service 
# journalctl -u puppet.service --follow
-- Logs begin at Thu 2019-10-17 14:28:35 NZDT. --
Nov 05 17:56:17 proc1 puppet[10533]: 
...
Nov 05 18:40:15 proc1 systemd[1]: Stopping Puppet agent...
Nov 05 18:40:15 proc1 puppet-agent[10533]: Caught TERM; exiting
Nov 05 18:40:15 proc1 systemd[1]: Stopped Puppet agent.
Nov 05 18:41:32 proc1 puppet-agent[823]: (Facter) error while resolving custom fact "docker_version": execution expired
Nov 05 18:41:41 proc1 puppet-agent[823]: Applied catalog in 1.39 seconds
Nov 05 18:42:30 proc1 systemd[1]: Started Puppet agent.
Nov 05 18:42:31 proc1 puppet-agent[11223]: Starting Puppet client version 6.10.1
Nov 05 18:42:45 proc1 puppet-agent[11229]: Applied catalog in 1.24 seconds
```

So when the service ran again it failed to run `docker_version` but this time correctly timed it out: `execution expired`. 

On the other system I tried a different tack. I killed the child docker process to see what would happen. The agent happily finished the run and then ran again immediately after being paused for 2 days:
```
# systemctl status puppet.service 
* puppet.service - Puppet agent
   Loaded: loaded (/lib/systemd/system/puppet.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-11-03 14:40:41 NZDT; 2 days ago
 Main PID: 709 (puppet)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/puppet.service
           `-709 /opt/puppetlabs/puppet/bin/ruby /opt/puppetlabs/puppet/bin/puppet agent --no-daemonize

Nov 03 14:40:44 test-supermicro puppet-agent[822]: Failed to open TCP connection to puppet.XXX:8140 (getaddrinfo: Temporary failure in name resolution)
Nov 03 14:40:44 test-supermicro puppet-agent[822]: (/File[/opt/puppetlabs/puppet/cache/facts.d]) Failed to generate additional resources using 'eval_generate': Failed to open TCP connection to puppet.XXX:8140 (getaddrinfo: Temporary failure in name resolution)
Nov 03 14:40:44 test-supermicro puppet-agent[822]: (/File[/opt/puppetlabs/puppet/cache/facts.d]) Could not evaluate: Could not retrieve file metadata for puppet:///pluginfacts: Failed to open TCP connection to puppet.XXX:8140 (getaddrinfo: Temporary failure in name resolution)
Nov 03 14:40:44 test-supermicro puppet-agent[822]: (/File[/opt/puppetlabs/puppet/cache/lib]) Failed to generate additional resources using 'eval_generate': Failed to open TCP connection to puppet.XXX:8140 (getaddrinfo: Temporary failure in name resolution)
Nov 03 14:40:44 test-supermicro puppet-agent[822]: (/File[/opt/puppetlabs/puppet/cache/lib]) Could not evaluate: Could not retrieve file metadata for puppet:///plugins: Failed to open TCP connection to puppet.XXX:8140 (getaddrinfo: Temporary failure in name resolution)
Nov 05 18:52:03 test-supermicro puppet-agent[822]: (Facter) error while resolving custom fact "docker_version": execution expired
Nov 05 18:52:09 test-supermicro puppet-agent[822]: Local environment: 'production' doesn't match server specified environment 'tannery_production', restarting agent run with environment 'tannery_production'
Nov 05 18:52:20 test-supermicro puppet-agent[822]: Applied catalog in 1.32 seconds
Nov 05 18:52:22 test-supermicro puppet-agent[4283]: Local environment: 'production' doesn't match server specified node environment 'tannery_production', switching agent to 'tannery_production'.
Nov 05 18:52:32 test-supermicro puppet-agent[4283]: Applied catalog in 1.26 seconds
```

**Comment by damonmaria** [comment]
FYI I can consistently make this happen with a reboot. I notice that (as you can see in the output above) when puppet first runs networking seems to not be up yet, and I wonder if something about that is causing `docker version` to hang?? 

There definitely seems to be ways to get docker into this situation:

- https://forums.docker.com/t/what-to-do-when-all-docker-commands-hang/28103/6
- https://forums.docker.com/t/all-docker-command-line-commands-hang/68118

So I think this module should be able to handle it. It seems it's trying to use some kind of timeout for the call but it doesn't work. The "execution expired" below is only reported when I kill the `docker version` process:
```
Nov 18 03:01:03 proc1 puppet-agent[874]: (/File[/opt/puppetlabs/puppet/cache/lib]) Could not evaluate: Could not retrieve file metadata for puppet:///plugins: Failed to open TCP connection to puppet.mindhive.cloud:8140 (getaddrinfo: Temporary failure in name resolution)
Nov 18 12:47:08 proc1 puppet-agent[874]: (Facter) error while resolving custom fact "docker_version": execution expired
```

**Comment by damonmaria** [comment]
I think I've found the root cause. systemd starts `puppet.service` before `docker.service` and the related socket unit, etc... Running the `docker --version` command before these units start up appears to cause `docker` to lock up and not recover. 

I've gotten around this by adding a drop-in file to puppet (`/etc/systemd/system/puppet.service.d/wait-for-docker.conf`):
```
[Unit]
After=docker.service
```
